export const data = [
	{
		name: "Marlango",
		price: "7000",
		category: "Wine",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Baron De Val",
		price: "4000",
		category: "Wine",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Baron Romero",
		price: "4000",
		category: "Wine",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Carlo Rossi",
		price: "7000",
		category: "Wine",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Monte Palacio",
		price: "4000",
		category: "Wine",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Pure Heaven",
		price: "4000",
		category: "Wine",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Eva Wine",
		price: "4000",
		category: "Wine",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Four Cousin Sweet",
		price: "6000",
		category: "Wine",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Millegrand",
		price: "7000",
		category: "Wine",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "JP. Chenet",
		price: "8000",
		category: "Wine",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Mateus Rose",
		price: "7000",
		category: "Wine",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Portell White",
		price: "6000",
		category: "Wine",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "De Clan White",
		price: "6000",
		category: "Wine",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "De Clan Red",
		price: "6000",
		category: "Wine",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Escudo Rojo",
		price: "18000",
		category: "Wine",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Black Doctor (Red Sweet)",
		price: "10000",
		category: "Wine",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Star Chaser (Red Wine)",
		price: "5000",
		category: "Wine",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Black Doctor (Red Wine)",
		price: "10000",
		category: "Wine",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Sun Chaser",
		price: "5000",
		category: "Wine",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Big Baily",
		price: "10000",
		category: "Irish Oream",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Small Best Cream",
		price: "1500",
		category: "Irish Oream",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Big Best Cream",
		price: "5000",
		category: "Irish Oream",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Andre Rose",
		price: "8000",
		category: "Champagne",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Andre Brut",
		price: "8000",
		category: "Champagne",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Fortell Ice",
		price: "6000",
		category: "Champagne",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "De Clan Ice",
		price: "5000",
		category: "Champagne",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Chamdor",
		price: "5000",
		category: "Champagne",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Martini Rose",
		price: "5000",
		category: "Champagne",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Zagg",
		price: "1000",
		category: "Energy Drink",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Monster",
		price: "1000",
		category: "Energy Drink",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Power Horse",
		price: "1000",
		category: "Energy Drink",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Amber E. Drink",
		price: "700",
		category: "Energy Drink",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Small Water",
		price: "200",
		category: "Soft Drinks",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Plastic Minerals",
		price: "300",
		category: "Soft Drinks",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "All Malt",
		price: "600",
		category: "Soft Drinks",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Fayrouz",
		price: "600",
		category: "Soft Drinks",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Chivita Juice",
		price: "1500",
		category: "Soft Drinks",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Holladia Yoghurt",
		price: "1500",
		category: "Soft Drinks",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
	{
		name: "Cedaa Yoghurt",
		price: "1500",
		category: "Soft Drinks",
		description: "",
		image: "/image/Soft Drinks/Holladia Yoghurt.jpg",
		section: "drink",
	},
];
